------------------------------------------------------------------------
-- Author:
--      Eddy Dushime
--
-- Implementation:
--     This package takes a filename to read from or write to. It allows 
--     for the exchange of data available from the user and data returned 
--     after image processing.
------------------------------------------------------------------------
